bot:
    tokken: xxxxxx.xxxxxxxx.xxxxxxxxxxx
    welcome:
        - Message multi-lignes
        - Exemple
        - >
            Tu es inconnu de nos services,
            Pour rejoindre $server, je t'invite a cliquer sur le lien
            suivant.
    logs: 1231231231321321312313
website:
    enable: True
    url:    http://127.0.0.1:8000
    token:  xxxxxxxxxxxxxxxxxxxxx
    time:   10
