bot:
    tokken: xxxxxx.xxxxxxxx.xxxxxxxxxxx
    welcome:
        - Message multi-lignes
        - Exemple 
        - >
            Tu es inconnu de nos services,
            Pour rejoindre ce serveur, je t'invite a cliquer sur le lien
            suivant.
    logs: "root channel with logs of all servers"
database:
    url: postgres://postgres@localhost/postgres
website:
    enable:     True
    url:        http://127.0.0.1:8000
    username:   admin
    password:   pass
servers:
    "server_id_here":
        logs:     "channel_id_here"
        admin:    "channel_id_here"
        rank: # ranks for authenticated users
            - "role_id_here"
            - "other_role_id"
        banned: # ranks for banned users
            - "role_id_here"
    "other_server":
        logs:     "channel_id_here"
        admin:    "channel_id_here"
        rank:
            - "role_id_here"
        banned:
            - "role_id_here"
