bot:
    tokken: xxxxxx.xxxxxxxx.xxxxxxxxxxx
    welcome:
        - Salut a toi !
        - >
            Tu es inconnu de nos services,
            Pour rejoindre ce serveur, je t'invite a cliquer sur le lien
            suivant.
    logs: "channel_id_here"
database:
    url: postgres://postgres@epilogin-db/postgres
website:
    url:        http://127.0.0.1:8000
    username:   admin
    password:   pass
servers:
    "server_id_here":
        logs:     "channel_id_here"
        admin:    "channel_id_here"
        rank:
            - "role_id_here"
